MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/gatsinzi/.cache/torch/hub/checkpoints/swin_base_patch4_window7_224_22kto1k.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('5')
  TRANSFORMER_TYPE: 'swin_base_patch4_window7_224_TransReID'
  STRIDE_SIZE: [4, 4]
  SIE_CAMERA: True
  SIE_COE: 3.0
  # JPM: True
  # RE_ARRANGE: True
  IS_SWIN: True
  SWIN_EMBED_DIM: 128
  SWIN_DEPTHS: [2, 2, 18, 2]
  SWIN_NUM_HEADS: [4, 8, 16, 32]
  SWIN_WINDOW_SIZE: 7
  SWIN_DROP_PATH_RATE: 0.5

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('../data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 16
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 50
  EVAL_PERIOD: 120
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '../logs/market_swin_transreid/swin_transformer_120.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: '../logs/market_swin_transreid'


